### ISSUE TITLE
Fail to test abs081_b in AtCoder Beginners Selection

### ISSUE THREAD

**Issue by zacky1972** [tamanugi/ex_at_coder#7]
1. `mix atcoder.new abs`
2. write the following code
3. `mix atcoder.test abs abc081_b`
4. Then, the results of all testing is `RE`.

```elixir:lib/abs/abc081_b.ex
defmodule Abs.ABC081B.Main do
  def main() do
    IO.puts(2)
  end
end
```

**Comment by zacky1972** [comment]
Thank you.
I tested it, but I got another error:

```
% mix atcoder.new abs            
* creating lib/abs
* creating lib/abs/practice_a.ex
* creating lib/abs/test_case
* creating lib/abs/test_case/practice_a.yml
* creating lib/abs/ab_c086_a.ex
* creating lib/abs/test_case/ab_c086_a.yml
* creating lib/abs/ab_c081_a.ex
* creating lib/abs/test_case/ab_c081_a.yml
* creating lib/abs/ab_c081_b.ex
* creating lib/abs/test_case/ab_c081_b.yml
* creating lib/abs/ab_c087_b.ex
* creating lib/abs/test_case/ab_c087_b.yml
* creating lib/abs/ab_c083_b.ex
* creating lib/abs/test_case/ab_c083_b.yml
* creating lib/abs/ab_c088_b.ex
* creating lib/abs/test_case/ab_c088_b.yml
* creating lib/abs/ab_c085_b.ex
* creating lib/abs/test_case/ab_c085_b.yml
* creating lib/abs/ab_c085_c.ex
* creating lib/abs/test_case/ab_c085_c.yml
* creating lib/abs/ab_c049_c.ex
* creating lib/abs/test_case/ab_c049_c.yml
* creating lib/abs/ab_c086_c.ex
* creating lib/abs/test_case/ab_c086_c.yml
✨ Generate code for abs
👍 Good Luck
zacky@zackym1air at_coder % mix atcoder.test abs abc081_b  
** (MatchError) no match of right hand side value: {:error, %YamlElixir.FileNotFoundError{message: "Failed to open file \"/Users/zacky/at_coder/lib/abs/test_case/abc081_b.yml\": no such file or directory"}}
    lib/mix/tasks/atcoder/test.ex:14: Mix.Tasks.Atcoder.Test.run/1
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/cli.ex:82: Mix.CLI.run_task/2
```

**Comment by tamanugi** [comment]
@zacky1972 

Thanks!
I could not reproduce issue on my project 🤔
Could you try `mix deps.clean` or delete `mix.lock` ?

**Comment by zacky1972** [comment]
I tested both, but the error is reproduced.

First, I tested `mix deps.clean` as follows:

```
Last login: Sun Aug 21 04:52:00 on ttys000
zacky@zackym1air ~ % cd at_coder
zacky@zackym1air at_coder % ls
README.md	bench		deps		lib		mix.lock
_build		cookie.txt	erl_crash.dump	mix.exs		test
zacky@zackym1air at_coder % ls lib 
abc138		abc263		abs		at_coder.ex
zacky@zackym1air at_coder % rm -rf lib/abs
zacky@zackym1air at_coder % mix deps.clean --all
* Cleaning benchee
* Cleaning browser_launcher
* Cleaning certifi
* Cleaning deep_merge
* Cleaning ex_at_coder
* Cleaning floki
* Cleaning hackney
* Cleaning html_entities
* Cleaning httpoison
* Cleaning idna
* Cleaning metrics
* Cleaning mimerl
* Cleaning parse_trans
* Cleaning ssl_verify_fun
* Cleaning statistex
* Cleaning unicode_util_compat
* Cleaning yamerl
* Cleaning yaml_elixir
zacky@zackym1air at_coder % mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  benchee 1.1.0
  browser_launcher 0.1.3
  certifi 2.9.0
  deep_merge 1.0.0
  ex_at_coder 0.2.4
  floki 0.29.0
  hackney 1.18.1
  html_entities 0.5.2
  httpoison 1.8.2
  idna 6.1.1
  metrics 1.0.1
  mimerl 1.2.0
  parse_trans 3.3.1
  ssl_verify_fun 1.1.6
  statistex 1.0.0
  unicode_util_compat 0.7.0
  yamerl 0.10.0
  yaml_elixir 2.9.0
* Getting ex_at_coder (Hex package)
* Getting benchee (Hex package)
* Getting deep_merge (Hex package)
* Getting statistex (Hex package)
* Getting browser_launcher (Hex package)
* Getting floki (Hex package)
* Getting httpoison (Hex package)
* Getting yaml_elixir (Hex package)
* Getting yamerl (Hex package)
* Getting hackney (Hex package)
* Getting certifi (Hex package)
* Getting idna (Hex package)
* Getting metrics (Hex package)
* Getting mimerl (Hex package)
* Getting parse_trans (Hex package)
* Getting ssl_verify_fun (Hex package)
* Getting unicode_util_compat (Hex package)
* Getting html_entities (Hex package)
zacky@zackym1air at_coder % mix atcoder.new abs
==> browser_launcher
Compiling 1 file (.ex)
Generated browser_launcher app
===> Compiling parse_trans
===> Compiling yamerl
===> Compiling mimerl
===> Compiling metrics
===> Compiling unicode_util_compat
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Compiling idna
==> deep_merge
Compiling 2 files (.ex)
Generated deep_merge app
==> ssl_verify_fun
Compiling 7 files (.erl)
Generated ssl_verify_fun app
==> yaml_elixir
Compiling 6 files (.ex)
Generated yaml_elixir app
==> html_entities
Compiling 2 files (.ex)
Generated html_entities app
==> floki
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 24 files (.ex)
Generated floki app
==> statistex
Compiling 3 files (.ex)
Generated statistex app
==> benchee
Compiling 44 files (.ex)
Generated benchee app
===> Compiling certifi
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Compiling hackney
==> httpoison
Compiling 3 files (.ex)
Generated httpoison app
==> ex_at_coder
Compiling 27 files (.ex)
Generated ex_at_coder app
==> at_coder
* creating lib/abs
* creating lib/abs/practice_a.ex
* creating lib/abs/test_case
* creating lib/abs/test_case/practice_a.yml
* creating lib/abs/ab_c086_a.ex
* creating lib/abs/test_case/ab_c086_a.yml
* creating lib/abs/ab_c081_a.ex
* creating lib/abs/test_case/ab_c081_a.yml
* creating lib/abs/ab_c081_b.ex
* creating lib/abs/test_case/ab_c081_b.yml
* creating lib/abs/ab_c087_b.ex
* creating lib/abs/test_case/ab_c087_b.yml
* creating lib/abs/ab_c083_b.ex
* creating lib/abs/test_case/ab_c083_b.yml
* creating lib/abs/ab_c088_b.ex
* creating lib/abs/test_case/ab_c088_b.yml
* creating lib/abs/ab_c085_b.ex
* creating lib/abs/test_case/ab_c085_b.yml
* creating lib/abs/ab_c085_c.ex
* creating lib/abs/test_case/ab_c085_c.yml
* creating lib/abs/ab_c049_c.ex
* creating lib/abs/test_case/ab_c049_c.yml
* creating lib/abs/ab_c086_c.ex
* creating lib/abs/test_case/ab_c086_c.yml
✨ Generate code for abs
👍 Good Luck
zacky@zackym1air at_coder % mix atcoder.test abs abc081_b
** (MatchError) no match of right hand side value: {:error, %YamlElixir.FileNotFoundError{message: "Failed to open file \"/Users/zacky/at_coder/lib/abs/test_case/abc081_b.yml\": no such file or directory"}}
    lib/mix/tasks/atcoder/test.ex:14: Mix.Tasks.Atcoder.Test.run/1
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/cli.ex:82: Mix.CLI.run_task/2
    (elixir 1.10.4) lib/code.ex:926: Code.require_file/2
zacky@zackym1air at_coder % 
```

Then, I tested `rm mix.lock` as follows:

```
Last login: Sun Aug 21 04:59:43 on ttys001
zacky@zackym1air ~ % cd at_coder
zacky@zackym1air at_coder % ls
README.md	bench		deps		lib		mix.lock
_build		cookie.txt	erl_crash.dump	mix.exs		test
zacky@zackym1air at_coder % ls lib 
abc138		abc263		abs		at_coder.ex
zacky@zackym1air at_coder % rm -rf lib/abs
zacky@zackym1air at_coder % rm mix.lock 
zacky@zackym1air at_coder % mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
New:
  benchee 1.1.0
  browser_launcher 0.1.3
  certifi 2.9.0
  deep_merge 1.0.0
  ex_at_coder 0.2.4
  floki 0.29.0
  hackney 1.18.1
  html_entities 0.5.2
  httpoison 1.8.2
  idna 6.1.1
  metrics 1.0.1
  mimerl 1.2.0
  parse_trans 3.3.1
  ssl_verify_fun 1.1.6
  statistex 1.0.0
  unicode_util_compat 0.7.0
  yamerl 0.10.0
  yaml_elixir 2.9.0
All dependencies are up to date
zacky@zackym1air at_coder % mix atcoder.new abs  
* creating lib/abs
* creating lib/abs/practice_a.ex
* creating lib/abs/test_case
* creating lib/abs/test_case/practice_a.yml
* creating lib/abs/ab_c086_a.ex
* creating lib/abs/test_case/ab_c086_a.yml
* creating lib/abs/ab_c081_a.ex
* creating lib/abs/test_case/ab_c081_a.yml
* creating lib/abs/ab_c081_b.ex
* creating lib/abs/test_case/ab_c081_b.yml
* creating lib/abs/ab_c087_b.ex
* creating lib/abs/test_case/ab_c087_b.yml
* creating lib/abs/ab_c083_b.ex
* creating lib/abs/test_case/ab_c083_b.yml
* creating lib/abs/ab_c088_b.ex
* creating lib/abs/test_case/ab_c088_b.yml
* creating lib/abs/ab_c085_b.ex
* creating lib/abs/test_case/ab_c085_b.yml
* creating lib/abs/ab_c085_c.ex
* creating lib/abs/test_case/ab_c085_c.yml
* creating lib/abs/ab_c049_c.ex
* creating lib/abs/test_case/ab_c049_c.yml
* creating lib/abs/ab_c086_c.ex
* creating lib/abs/test_case/ab_c086_c.yml
✨ Generate code for abs
👍 Good Luck
zacky@zackym1air at_coder % mix atcoder.test abs abc081_b 
** (MatchError) no match of right hand side value: {:error, %YamlElixir.FileNotFoundError{message: "Failed to open file \"/Users/zacky/at_coder/lib/abs/test_case/abc081_b.yml\": no such file or directory"}}
    lib/mix/tasks/atcoder/test.ex:14: Mix.Tasks.Atcoder.Test.run/1
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/cli.ex:82: Mix.CLI.run_task/2
    (elixir 1.10.4) lib/code.ex:926: Code.require_file/2
zacky@zackym1air at_coder % 
```
